-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'client',
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for courts
create table courts (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null, -- 'Singles', 'Doubles'
  location text,
  hourly_rate numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table courts enable row level security;
create policy "Courts are viewable by everyone." on courts for select using (true);

-- Create a table for bookings
create table bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  court_id bigint references courts(id) not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status text default 'confirmed', -- 'confirmed', 'cancelled', 'completed'
  total_price numeric,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table bookings enable row level security;

create policy "Users can view own bookings." on bookings
  for select using (auth.uid() = user_id);

create policy "Users can create bookings." on bookings
  for insert with check (auth.uid() = user_id);

-- Admin policies (Simplified for demo: assuming admin has a specific email or role check)
-- In a real app, you'd use a custom claim or a separate admins table.
-- For now, we'll allow all authenticated users to read bookings for the dashboard demo,
-- but strictly speaking you'd want: auth.jwt() ->> 'role' = 'admin'
create policy "Admins can view all bookings" on bookings
    for select using ( auth.jwt() ->> 'email' = 'jashu@example.com' ); 
